// Design System Constants
export const DS = {
  colors: {
    bg: '#F7F5F0',
    card: '#FFFFFF',
    navy: '#0D1F3C',
    navyMid: '#1A3A6B',
    gold: '#C4963E',
    goldLight: '#F0DFA0',
    goldBg: '#FBF4E0',
    muted: '#6B7A99',
    mutedLight: '#E8EAF0',
    border: 'rgba(13,31,60,0.08)',
    borderStrong: 'rgba(13,31,60,0.16)',
    success: '#1A7A50',
    successLight: '#E6F4EE',
    error: '#B93B2B',
    errorLight: '#FBE9E7',
    bronze: '#B87333',
    bronzeBg: '#FAEEE3',
    silver: '#9EA3A8',
    silverBg: '#F0F1F2',
    goldTier: '#C4963E',
    goldTierBg: '#FBF4E0',
    platinum: '#8B7CB6',
    platinumBg: '#F0EDF8',
  },
  radii: { sm: 8, md: 14, lg: 20, xl: 28 },
  shadow: {
    sm: '0 1px 4px rgba(13,31,60,0.06)',
    md: '0 4px 16px rgba(13,31,60,0.09)',
    lg: '0 8px 32px rgba(13,31,60,0.13)',
    gold: '0 4px 20px rgba(196,150,62,0.28)',
  },
  tiers: {
    bronze: { ar: 'برونز', en: 'Bronze', color: '#B87333', bg: '#FAEEE3', range: '100–400' },
    silver: { ar: 'فضي', en: 'Silver', color: '#9EA3A8', bg: '#F0F1F2', range: '400–600' },
    gold: { ar: 'ذهبي', en: 'Gold', color: '#C4963E', bg: '#FBF4E0', range: '600–800' },
    platinum: { ar: 'بلاتيني', en: 'Platinum', color: '#8B7CB6', bg: '#F0EDF8', range: '800–1000' },
  },
  getTier: (s: number): 'bronze' | 'silver' | 'gold' | 'platinum' => 
    s < 400 ? 'bronze' : s < 600 ? 'silver' : s < 800 ? 'gold' : 'platinum',
};

export const STRINGS = {
  ar: {
    appName: 'جمعية AI',
    tagline: 'دوائر الادخار الذكية',
    dashboard: 'الرئيسية',
    marketplace: 'السوق',
    myCircles: 'جمعياتي',
    create: 'أنشئ',
    trustScore: 'درجة الثقة',
    wallet: 'المحفظة',
    balance: 'الرصيد',
    continue: 'متابعة',
    back: 'رجوع',
    join: 'انضم الآن',
    signUp: 'إنشاء حساب',
    signIn: 'تسجيل الدخول',
    jod: 'د.أ',
    month: 'شهر',
    monthly: '/شهر',
    members: 'عضو',
    turn: 'الدور',
    yourTurn: 'دورك القادم',
    viewAll: 'عرض الكل',
    search: 'ابحث في السوق...',
    filter: 'تصفية',
    send: 'إرسال',
    askAI: 'اسأل المساعد الذكي...',
    paid: 'مدفوع',
    pending: 'معلق',
    late: 'متأخر',
    active: 'نشط',
    completed: 'مكتمل',
    private: 'خاص',
    semiPublic: 'شبه عام',
    public: 'عام',
    amount: 'المبلغ',
    duration: 'المدة',
    minScore: 'أدنى درجة ثقة',
    smartMatch: 'تطابق ذكي',
    insurance: 'صندوق التأمين',
    confettiMsg: '!مبروك! استلمت دورك',
    verifyPhone: 'تحقق من هاتفك',
    uploadId: 'تحميل الهوية الوطنية',
    takeSelfie: 'التقاط صورة شخصية',
    scoreReveal: 'درجة ثقتك الأولية',
    enterOtp: 'أدخل رمز التحقق المرسل إلى',
    analyzeId: '...جاري تحليل هويتك بالذكاء الاصطناعي',
    calculating: '...جاري حساب درجة ثقتك',
    congratsScore: '!أهلاً بك في جمعية AI',
    goToDashboard: 'الذهاب إلى الرئيسية',
    payoutMsg: '!يوم الصرف وصل',
    insuranceKickedIn: 'تدخّل صندوق التأمين',
    defaultMsg: 'عضو تأخر عن الدفع — غطّى صندوق التأمين الفرق تلقائياً وتلقائياً',
    slots: 'مقاعد متبقية',
    slotsUnit: '',
    step: 'الخطوة',
    of: 'من',
    typeCircle: 'نوع الجمعية',
    detailsCircle: 'تفاصيل الجمعية',
    allocationCircle: 'توزيع الأدوار',
    inviteCircle: 'دعوة الأعضاء',
    name: 'الاسم',
    desc: 'الوصف',
    nextMonth: 'الشهر القادم',
    totalPot: 'إجمالي الصندوق',
    insuranceFund: 'صندوق التأمين',
    myTurn: 'دوري',
    paidMembers: 'أعضاء دفعوا',
    groupChat: 'المحادثة الجماعية',
    paymentTimeline: 'جدول المدفوعات',
    you: 'أنت',
    received: 'استلم',
  },
  en: {
    appName: "Jam'iyya AI",
    tagline: 'Smart Savings Circles',
    dashboard: 'Home',
    marketplace: 'Marketplace',
    myCircles: 'My Circles',
    create: 'Create',
    trustScore: 'Trust Score',
    wallet: 'Wallet',
    balance: 'Balance',
    continue: 'Continue',
    back: 'Back',
    join: 'Join Now',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    jod: 'JOD',
    month: 'month',
    monthly: '/mo',
    members: 'members',
    turn: 'Turn',
    yourTurn: 'Your Next Turn',
    viewAll: 'View All',
    search: 'Search marketplace...',
    filter: 'Filter',
    send: 'Send',
    askAI: 'Ask AI assistant...',
    paid: 'Paid',
    pending: 'Pending',
    late: 'Late',
    active: 'Active',
    completed: 'Completed',
    private: 'Private',
    semiPublic: 'Semi-Public',
    public: 'Public',
    amount: 'Amount',
    duration: 'Duration',
    minScore: 'Min Trust Score',
    smartMatch: 'Smart Match',
    insurance: 'Insurance Fund',
    confettiMsg: 'Congratulations! Your payout is here!',
    verifyPhone: 'Verify Your Phone',
    uploadId: 'Upload National ID',
    takeSelfie: 'Take a Selfie',
    scoreReveal: 'Your Initial Trust Score',
    enterOtp: 'Enter the code sent to',
    analyzeId: 'AI is analyzing your identity...',
    calculating: 'Calculating your trust score...',
    congratsScore: "Welcome to Jam'iyya AI!",
    goToDashboard: 'Go to Dashboard',
    payoutMsg: 'Payout day is here!',
    insuranceKickedIn: 'Insurance Fund Activated',
    defaultMsg:
      'A member missed their payment — our Insurance Fund covered the difference automatically',
    slots: 'spots left',
    slotsUnit: '',
    step: 'Step',
    of: 'of',
    typeCircle: 'Circle Type',
    detailsCircle: 'Circle Details',
    allocationCircle: 'Turn Allocation',
    inviteCircle: 'Invite Members',
    name: 'Name',
    desc: 'Description',
    nextMonth: 'Next Month',
    totalPot: 'Total Pot',
    insuranceFund: 'Insurance Fund',
    myTurn: 'My Turn',
    paidMembers: 'Members Paid',
    groupChat: 'Group Chat',
    paymentTimeline: 'Payment Timeline',
    you: 'You',
    received: 'Received',
  },
};

export const THEME_MAP = {
  wedding: { bg: '#FFF0F5', icon: '◇', color: '#D06080' },
  business: { bg: '#EFF5FF', icon: '◈', color: '#3060B0' },
  hajj: { bg: '#F5F0FF', icon: '◉', color: '#7060C0' },
  home: { bg: '#F0FFF5', icon: '▣', color: '#308060' },
  eid: { bg: '#FFFBF0', icon: '✦', color: '#C08030' },
};
